# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

METROSummaryStats <- function(betaeQTLin, betaGWASin, Dzin, Din, nzin, n, nu, hthre, maxIter, tol, verbose) {
    .Call(`_METRO_METROSummaryStats`, betaeQTLin, betaGWASin, Dzin, Din, nzin, n, nu, hthre, maxIter, tol, verbose)
}

